sonar.projectKey=devops-demo
sonar.projectName=DevOps Demo Java App
sonar.projectVersion=1.0
sonar.sources=src
sonar.java.binaries=.
sonar.host.url=http://localhost:9000
sonar.login=sqa_01cd847d3e1b2a091ff5a52eb8af9ac99e974b83
